
prepare_demographic_for_model <- function(
    migration, 
    fertility, 
    mortality, 
    population_all, 
    population_female,
    year_start = "",
    year_end = "",
    population_modifier = 1,
    fertility_modifier = 1,
    death_modifier = 1,
    migration_modifier = 1
  ){
  
  #Set year subset
  years <- if(year_start == "" & year_end == ""){
    as.numeric(min(migration$year, na.rm = T)):as.numeric(max(migration$year, na.rm = T))
  } else if(year_start != "" & year_end == ""){
    as.numeric(year_start):as.numeric(max(migration$year, na.rm = T))
  } else if(year_start == "" & year_end != ""){
    as.numeric(min(migration$year, na.rm = T)):as.numeric(year_end)
  } else if(year_start != "" & year_end != ""){
    as.numeric(year_start):as.numeric(year_end)
  }
  
  #Yearly changes
  #Run for 60 years
  time_run_for <- length(years)
  time_all <- seq(from = 0, length.out = time_run_for)

  #Subset population to the years of interest
  total_population_data <- population_all %>%
    filter(year %in% years) %>%
    select(x0:x100) * population_modifier
  
  population_all <- total_population_data %>% 
    as.matrix %>%
    rowSums() %>%
    c
  
  #Work out mortality
  mortality_change <- mortality %>%
    filter(year %in% years) %>%
    select(x0:x100)
  
  #Transform the mortality to the create ratio
  mortality_correct_format <- mortality_change/total_population_data
  #Remove values generated by dividing by zero
  is.na(mortality_correct_format)<-sapply(mortality_correct_format, is.infinite)
  mortality_correct_format[is.na(mortality_correct_format)] <- 1
  #Convert to a vector and make sure no values are above 1
  mortality_vector <- mortality_correct_format %>%
    as.matrix %>%
    t %>%
    c %>%
    pmin(1)
  
  #Work out fertility 
  population_female_matched <- population_female %>%
    filter(year %in% years) %>%
    select(x15:x49) %>%
    as.matrix * population_modifier
  
  fertility_matched <- fertility %>%
    filter(year %in% years) %>%
    select(x15:x49) %>%
    as.matrix * fertility_modifier
  
  #Fertility calculations to work out the births needed for the model
  fertility_by_year <- rowSums((fertility_matched/1000 * population_female_matched))/rowSums(population_female_matched)
  
  #Calculate migration
  palestine_migration <- migration %>%
    filter(year %in% years) %>%
    select(net_migration_rate_per_1_000_population) %>%
    set_names("migration_per_1000") %>%
    as.matrix %>%
    c * migration_modifier %>%
    as.numeric
  
  #Work out migration by year
  migration <- round(do.call(rbind, sapply(1:nrow(total_population_data), function(x){
    total_population_data[x,] * palestine_migration[x]/1000 
  }, simplify = F)) * 1000, 0)
  
  #Expanded grid for inputting into the model
  migration_expanded_grid <- do.call(rbind, sapply(1:60, function(x){
    data.frame(dim1 = x, dim2 = 1:101, dim3 = 1, dim4 = 1, value = as.numeric(migration[x, ]))
  }, simplify = FALSE))
  
  #Output
  list(
    N0 = array(c(unlist(round(total_population_data[1, ] * 1000, 0))), dim = c(101, 1, 1)),
    crude_birth = array(fertility_by_year, dim = c(length(time_all), 1)),
    crude_death = array(mortality_vector, dim = c(length(time_all), 101, 1)),
    tt_migration = time_all,
    migration_in_number = migration_expanded_grid,
    population_data = total_population_data,
    years = years
  )
  
}